export { default as SliderComponent } from './SliderComponent'
export { default as Sorting } from './Sorting'
export { default as Category } from './Category'
export { default as Products } from './Products'
export { default as BasketComp } from './BasketComp'
export { default as Manufacture } from './Manufacture'
export { default as Advantages } from './Advantages'